spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    log-validation-errors: true
    connection-init-sql: "SELECT 1 "
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false

ctrip:
  appid: 100003171
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE