spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  jpa:
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
server:
  port: 8070
  
logging:
  file: /opt/logs/100003173/apollo-portal.log
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


